name: CI Process

on:
  push:
    branches: [master]

jobs:
  test:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install environment
        run: yarn install

      - name: Run linters
        run: yarn lint

      - name: Run unit tests
        run: yarn test

